name: port_dart
description: Meu site em flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.0.0
  font_awesome_flutter: ^8.11.0
  url_launcher: ^6.0.2
  graphql_flutter: ^4.0.1
  flutter_dotenv: ^3.1.0
  hexcolor: ^2.0.0
  google_fonts: ^1.1.2
  shared_preferences: ^0.5.12+4
  flutter_modular: ^3.0.1
  rxdart: ^0.24.1
  bloc_pattern: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  build_test: ^1.3.0
  build_web_compilers: ^2.12.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - .env
